### ISSUE TITLE
Facebook Dataloader

### ISSUE THREAD

**Issue by dav-is** [alidcastano/druid.js#9]
Could we use https://github.com/facebook/dataloader to allow any kind of database instead of just SQL?

I would like to use a noSQL database.

**Comment by alidcast** [comment]
i'm pretty sure dataloader is used in conjunction with a databse orm, and doesn't replace it

so the limiting factor here is Objection. Druid could potentially support Mongo, but it's not a priority right now tbh

**Comment by dav-is** [comment]
Dataloader allows for an easy way of batching and caching, which is especially useful for graphql. I think it would be possible to use Dataloader in the framework, but also allow objection to be switched to mongoose or whatever is needed.

You might find this repo interesting: https://github.com/entria/graphql-dataloader-boilerplate

As a note, I was able to take this boilerplate and make it work with Google Datastore, a proprietary noSQL database. I had to rip out mongoose but it wasn’t too hard to do because of Dataloader.

**Comment by alidcast** [comment]
Personally, i don't think using a nosql database is a good move; in most non-trivial use cases, an sql databae is a much better choice... mongo might be easier to use, but I think with graphql that's no longer a concern

And yeah I was hoping to integrate data loader later on when having more time, but right now the app I'm building is still in its early stages and I'm not yet facing any scaling bottlenecks (nor are any users of druid) to justify spending time on this atm, sorry 

Thanks for the link, I'll keep it in mind for when I do get around to this

**Comment by dav-is** [comment]
I’ve found sql databases don’t scale well (sharding, migrations, data replication so difficult horizontal scaling). NoSQL databases have the same relationships, it’s just enforced at the software level instead of having a schema on the database and in the code, it’s only in the code.
